### ISSUE TITLE
film

### ISSUE THREAD

**Issue by SovietUfo** [Diamux/wolnoscod5g#1]
ogółem to bill_gate.mp4 ma ukryty ten interfejs od pauzowania filmu itp. i trzeba prawym kliknac zeby dalo sie to otworzyc a na telefonie w ogole sie nie da tego odtworzyc tego![Screenshot_20210322-160643_Chrome.jpg](https://user-images.githubusercontent.com/77695657/112011845-f2990780-8b28-11eb-905b-18d518d6034c.jpg)

**Comment by F1lippu** [comment]
rucham

**Comment by SovietUfo** [comment]
sram

**Comment by F1lippu** [comment]
no
